version: '3.5'

services:

  redis:
    container_name: redis
    image: bitnami/redis:5.0.6
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis
    ports:
      - 6379:6379
    volumes:
      - ${VOLUME_PATH}/redis/:/data

  commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis
    ports:
      - 8081:8081

networks:

  redis:
    name: redis
    driver: bridge