version: '3.5'

services:

  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - ${VOLUME_PATH}/mongo/:/data/db

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo_express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo
    ports:
      - 8083:8081

networks:

  mongo:
    name: mongo
    driver: bridge