version: '3'

services:

  mysql_master:
    image: mysql:5.7
    container_name: mysql_master
    restart: unless-stopped
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_PORT=3306
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=example
     - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - 4406:3306
    volumes:
      - ./configs/master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ${VOLUME_PATH}/mysql_master/data/:/var/lib/mysql/
    networks:
      - mysql-replication

  mysql_slave:
    image: mysql:5.7
    container_name: mysql_slave
    restart: unless-stopped
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_PORT=3306
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=example
     - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./configs/slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ${VOLUME_PATH}/mysql_slave/data/:/var/lib/mysql/
    networks:
      - mysql-replication

networks:

  mysql-replication:
    name: mysql-replication
    driver: bridge