version: '3.5'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    networks:
      - portainer
    ports:
      - 9000:9000
    volumes:
      - ${VOLUME_PATH}/portainer/:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:

  portainer:
    name: portainer
    driver: bridge