version: '3.5'

services:

  nginx:
    container_name: nginx
    image: nginx:stable
    restart: unless-stopped
    depends_on:
      - php56
      - php70
      - php71
      - php72
      - php73
      - php74
    networks:
      - nginx
      - php
    ports:
      - 8080:80
    volumes:
      - ${VOLUME_PATH}/sites/:/usr/share/nginx

  php56:
    container_name: php-5.6
    image: nanoninja/php-fpm:5.6
    restart: unless-stopped
    networks:
      - php
    volumes:
      #      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${VOLUME_PATH}/sites/:/web

  php70:
    container_name: php-7.0
    image: nanoninja/php-fpm:7.0
    restart: unless-stopped
    networks:
      - php
    volumes:
      #      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${VOLUME_PATH}/sites/:/web

  php71:
    container_name: php-7.1
    image: nanoninja/php-fpm:7.1
    restart: unless-stopped
    networks:
      - php
    volumes:
      #      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${VOLUME_PATH}/sites/:/web

  php72:
    container_name: php-7.2
    image: nanoninja/php-fpm:7.2
    restart: unless-stopped
    networks:
      - php
    volumes:
      #      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${VOLUME_PATH}/sites/:/web

  php73:
    container_name: php-7.3
    image: nanoninja/php-fpm:7.3
    restart: unless-stopped
    networks:
      - php
    volumes:
      #      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${VOLUME_PATH}/sites/:/web

  php74:
    container_name: php-7.4
    image: nanoninja/php-fpm:7.4
    restart: unless-stopped
    networks:
      - php
    volumes:
      #      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${VOLUME_PATH}/sites/:/web

networks:

  nginx:
    name: nginx
    driver: bridge

  php:
    name: php
    driver: bridge