version: '3.5'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=example
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - ${VOLUME_PATH}/mysql/:/var/lib/mysql/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    networks:
      - mysql
    depends_on:
      - mysql
    external_links:
      - mysql:db
    ports:
      - '8082:80'

networks:

  mysql:
    name: mysql
    driver: bridge